### ISSUE TITLE
forum: limited to 3 attachments per post?

### ISSUE THREAD

**Issue by knorker** [love2d/website#10]
Hi,
I wanted to update the thread of my game with a new release. However, I can not add another attachment: 
The "select file" window opens, I select the file - and then nothing happens. No error, attachment is not added.

I tested and noticed it seems only possible to attach three attachments per post. A workaround would be to make a new thread or post but I think it is nicer to have one thread per game with all releases in the startpost. 

Maybe it is just a setting in phpBB:
https://www.inmotionhosting.com/support/edu/phpbb/attachment-settings/
"Maximum number of attachments per post"

**Comment by TheLinx** [comment]
Because of imgur restricting its use as an image host I've increased the attachment limit to 10 files per post.
