### ISSUE TITLE
AppImage x86_64 under linux only partially clickable

### ISSUE THREAD

**Issue by c373** [love2d/website#13]
In section with id="download" under the linux links, the link for app image is only clickable from x86... on.

Current relevant code:
`AppImage <a href="https://github.com/love2d/love/releases/download/11.4/love-11.4-x86_64.AppImage">x86_64</a>`

Proposed change:
`<a href="https://github.com/love2d/love/releases/download/11.4/love-11.4-x86_64.AppImage">AppImage x86_64</a>`

This will make it so the entire section is a clickable link. I've had trouble in the past thinking that the link was broken or non-existent.

**Comment by bartbes** [comment]
Now we've only got 1 architecture that makes a lot of sense. The fix should be live now.
