### ISSUE TITLE
Activation Mails Not Working

### ISSUE THREAD

**Issue by LuminoByte** [love2d/website#17]
Hello, the activation mails for the forums aren't working. The first time i tried was the 10th of June. At that time i tried to resend it multiple times and make a different account, and it still didn't send.

It's now the 16th, i've tried to resend it again, and it's still not working.
Could you guys please manually activate my account? The username is 'Miel Land' It'd be greatly appreciated! Thank you.

**Comment by TheLinx** [comment]
I've given you a manual activation. I'll take a look at why the verification email could fail later.

**Comment by LuminoByte** [comment]
Perfect, thank you!

**Comment by TheLinx** [comment]
I sent myself a test email and it arrived without issue locally and on GMail.
GMail has no complaints about the email (PASS on SPF, PASS on DKIM, PASS on DMARC). Mail-tester.com gives the verification email a 10/10.

I found the outgoing emails to you in the server logs and they were all delivered with the comment "Queued mail for delivery -> 250 2.1.5"
Apparently that means Microsoft has an issue with it.

Microsoft has a service where you can check your server's reputation, but I signed up and saw it has no complaints about the server's IP.
I tried looking up more info about why your email was blocked but apparently "mail traffic and spam data may not be present for IPs which sent less than 100 messages on the given day." (we never send that much to outlook :) )

I'm going to send an email to Microsoft and see what they have to say, but I'm not going to expect any response as such a small-time operation. For now, I'm closing this issue as I'm 99% sure it's not our fault.

**Comment by LuminoByte** [comment]
Perfect! Appreciate you a ton.
