### ISSUE TITLE
Remove link to the old IRC channel from the homepage

### ISSUE THREAD

**Issue by slime73** [love2d/website#18]
The old LÖVE IRC channel is now defunct and no longer maintained in an official capacity. https://love2d.org/ should stop referencing it - maybe the text there about it could be changed from "and an IRC channel #love@irc.oftc.net" to "and a [subreddit](https://www.reddit.com/r/love2d)" or something, since that's been around for a while and is more maintained than the IRC channel.

**Comment by bartbes** [comment]
Applied during the 11.5 release.
