### ISSUE TITLE
Website suggestion: Add more games to front page

### ISSUE THREAD

**Issue by protbox** [love2d/website#19]
With more and more excellent games being released using LOVE, I think it's important to highlight them on the front page. Some that come to mind are:

Gravity Circuit: https://store.steampowered.com/app/858710/Gravity_Circuit/
Demonizer: https://store.steampowered.com/app/1091390/Demonizer/
EAT GIRL: https://tesselode.itch.io/eatgirl

Thanks!

**Comment by slime73** [comment]
The list on the homepage has been updated with some more modern releases.
