### ISSUE TITLE
Canvas:renderTo is documented incorrectly

### ISSUE THREAD

**Issue by lolbinarycat** [love2d/website#20]
i know i could make a forum account and fix the docs but i really don't feel like making a new account right now, sorry.

[the api docs](https://www.love2d.org/wiki/Canvas:renderTo) say that the function sets the current canvas to point to the screen afterwards, but actually it resores it to the previous value.

the equivelent lua would be this:

```
local oldcanvas = love.graphics.getCanvas()
love.graphics.setCanvas( canvas )
func()
love.graphics.setCanvas(oldcanvas)
```

the described behavior seemed wrong and likely to introduce subtle bugs, i was going to file a bug report to change the behavior, but first checked [where the function is defined in the source code](https://github.com/love2d/love/blob/0df51cf74376c7bf0e8479c276041e5c8e0f7b6b/src/modules/graphics/wrap_Canvas.cpp#L41), to see if the documentation was incorrect (it is).

**Comment by lolbinarycat** [comment]
in case it isn't clear when this difference matters: calling renderTo when the output canvas has already been changed.

**Comment by slime73** [comment]
I've edited the wiki page, but like the readme here says anyone with a forum account can do the same. The git repositories here are for source code and functionality rather than documentation work.

**Comment by zorggn** [comment]
Alternatively there's also a Discord server you could have posted this on.
