### ISSUE TITLE
Lots of pages throwing internal errors 

### ISSUE THREAD

**Issue by josh-perry** [love2d/website#24]
![Screenshot_20240703-182141.png](https://github.com/love2d/website/assets/6598916/0a7b2bda-c2dc-407f-8844-8ad40b6d1671)

For instance: https://love2d.org/wiki/love.system

**Comment by Muragami** [comment]
Looks like a simple PHP upgrade that broke things, they removed support for the format if implode() being used. See: [PHP implode](https://www.php.net/manual/en/function.implode.php). Hopefully not a hard fix once someone with access can do it (I'd guess updating mediawiki or such)

**Comment by TheLinx** [comment]
Sorry about that, and thanks for the tip. It should be working now. Let me know if anything else is broken.
